### ISSUE TITLE
Incorrect Command Suggested to Fix Unmet Dependencies

### ISSUE THREAD

**Issue by digitalcoyote** [Debian/apt#87] opened 2019-03-09 03:53 UTC
It appears that when you have unmet dependencies, it tells you to run a command backwards.

> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> You might want to run 'apt --fix-broken install' to correct these.
> The following packages have unmet dependencies:
>  mono-complete : Depends: ca-certificates-mono (= 5.18.0.268-0xamarin7+ubuntu1804b1) but 5.18.0.240-0xamarin1+ubuntu1804b1 is installed
>  mono-devel : Depends: ca-certificates-mono (= 5.18.0.268-0xamarin7+ubuntu1804b1) but 5.18.0.240-0xamarin1+ubuntu1804b1 is installed
> E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

Running the suggested command results in:

> sudo apt --fix-broken install
> apt
> Usage: apt command [options]
>        apt help command [options]
> 
> Commands:
>   add-repository   - Add entries to apt sources.list
>   autoclean        - Erase old downloaded archive files
>   autoremove       - Remove automatically all unused packages
>   build            - Build binary or source packages from sources
>   build-dep        - Configure build-dependencies for source packages
>   changelog        - View a package's changelog
>   check            - Verify that there are no broken dependencies
>   clean            - Erase downloaded archive files
>   contains         - List packages containing a file
>   content          - List files contained in a package
>   deb              - Install a .deb package
>   depends          - Show raw dependency information for a package
>   dist-upgrade     - Upgrade the system by removing/installing/upgrading packages
>   download         - Download the .deb file for a package
>   edit-sources     - Edit /etc/apt/sources.list with your preferred text editor
>   dselect-upgrade  - Follow dselect selections
>   full-upgrade     - Same as 'dist-upgrade'
>   held             - List all held packages
>   help             - Show help for a command
>   hold             - Hold a package
>   install          - Install/upgrade packages
>   list             - List packages based on package names
>   policy           - Show policy settings
>   purge            - Remove packages and their configuration files
>   recommends       - List missing recommended packages for a particular package
>   rdepends         - Show reverse dependency information for a package
>   reinstall        - Download and (possibly) reinstall a currently installed package
>   remove           - Remove packages
>   search           - Search for a package by name and/or expression
>   show             - Display detailed information about a package
>   showhold         - Same as 'held'
>   source           - Download source archives
>   sources          - Same as 'edit-sources'
>   unhold           - Unhold a package
>   update           - Download lists of new/upgradable packages
>   upgrade          - Perform a safe upgrade
>   version          - Show the installed version of a package
> 

I believe it should say:

> You might want to run 'apt install --fix-broken' to correct these.

**Comment by DonKult** [comment] 2019-03-10 18:57
Our binary `apt` like all other tools support `command --flag subcommand` – so `apt --fix-broken install` is perfectly valid and works™.

You aren't using our `apt` binary through as it has an entirely different output on `apt --help` (or misuse). I would advice dropping the local script you have installed shadowing our `apt` if you want to use it. Either way, closing as not a bug (in our tools).

**Closed by DonKult** 2019-03-10 18:57 UTC
