### ISSUE TITLE
requesting updated versions

### ISSUE THREAD

**Issue by tiagomoraismorgado88** [Debian/apt#58] opened 2018-01-03 18:45 UTC
greetings
i would kindly like to request updated vesions of the following software, ready to be installed from the package manager)
- supercollider (current version is 3.9, repository features 3.7)
- pd-2lork (only featuring an old version of puredata)
- audacity -> current version recurrently has problems with glithces
- musescore (current version is deprecated(
- openarena (mirrors are not currently properly allocated)
- processing (doesnt even feature it)
- qt/creator / qml
- vscode
- sublime text
- atom

**Comment by DonKult** [comment] 2018-01-03 18:55
This is the code repository for the package manager "apt" as used by Debian (and many many of its derivatives and then some). We don't maintain the packages you can install with apt, nor have we any impact on the maintainers of those packages. You will want to report a bug against the packages in the Debian Bug Tracking System (BTS).

Also, some of the "not current" can probably be attributed to you using "Debian stable" where the whole point of the exercise is to not introduce new versions of packages at random points in time. You will want to look into backports for this. Anyhow, that is more of a support topic and the fine manual/release notes explain this in far more detail than I ever could.

As this is not a bug in apt, closing as such (just that I can't official close this report ATM).

**Closed** 2018-01-03 19:16 UTC

**Comment by tiagomoraismorgado88** [comment] 2018-01-04 12:19
@DonKult  thank you for your precious insights on the topic
