### ISSUE TITLE
apt-get keeps upgrading the same package over and over again

### ISSUE THREAD

**Issue by jean-christophe-manciot** [Debian/apt#23] opened 2016-09-18 10:31 UTC
I have my own public [PPA](https://gitlab.com/jean-christophe-manciot/ppa) which hosts ~ 1000 different deb packages and apt is one of them. I build all of them with my own scripts, for instance for apt @ https://github.com/Debian/apt (latest stable release 1.2.14):
```
        echo --------
        echo Cleaning
        echo --------
        cd git-apt
        git checkout master
        git reset --hard
        git clean -fxd :/
        git pull -v --progress --rebase
        git checkout ${release_number}

        echo ---------------------------
        echo Checking Build Dependencies
        echo ---------------------------
        dpkg-checkbuilddeps

        echo --------
        echo Building
        echo --------
        dpkg-buildpackage -b -m"Jean-Christophe Manciot <manciot.jeanchristophe@gmail.com>"
```
Apt has a very strange behavior for only 3 of them: it always considers than even after upgrade, the local  package needs to be upgraded again from my PPA, meaning that it loops into asking the same question over and over:
```
apt-get update
apt-get upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  libgegl-0.3-0 network-manager-strongswan ntopng
3 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
...
Do you want to continue? [Y/n] 
```
I have **no such issue with any of the others**:

I have asked about this issue online on multiple well-informed forums, but no one knows what is going on.
This issue remains even when I build more recent versions of the 3 packages and push them up to the PPA.
The following **apt-get policy** information shows the peculiarity of those 3 packages as compared to  2 other packages with which I have no issue whatsoever (apt & git):
```
apt policy network-manager-strongswan
network-manager-strongswan:
  Installed: 1.3.1-14
  Candidate: 1.3.1-14
  Version table:
     **1.3.1-14 500
        500 https://gitlab.com/jean-christophe-manciot/ppa/raw/master/Ubuntu xenial/stable amd64 Packages
 *** 1.3.1-14 100
        100 /var/lib/dpkg/status**
     1.3.1-1ubuntu1 500
        500 http://bouyguestelecom.ubuntu.lafibre.info/ubuntu xenial/universe amd64 Packages

apt policy ntopng
ntopng:
  Installed: 2.4.1~git20160917.6bd1fee-14
  Candidate: 2.4.1~git20160917.6bd1fee-14
  Version table:
     **2.4.1~git20160917.6bd1fee-14 500
        500 https://gitlab.com/jean-christophe-manciot/ppa/raw/master/Ubuntu xenial/stable amd64 Packages
 *** 2.4.1~git20160917.6bd1fee-14 100
        100 /var/lib/dpkg/status**
     2.4.1~git20160827.22aaa53-15 500
        500 https://gitlab.com/jean-christophe-manciot/ppa/raw/master/Ubuntu xenial/stable amd64 Packages
     2.2+dfsg1-1build1 500
        500 http://bouyguestelecom.ubuntu.lafibre.info/ubuntu xenial/universe amd64 Packages

apt policy libgegl-0.3-0
libgegl-0.3-0:
  Installed: 0.3.9~git20160915.eb33c65-14
  Candidate: 0.3.9~git20160915.eb33c65-14
  Version table:
     **0.3.9~git20160915.eb33c65-14 500
        500 https://gitlab.com/jean-christophe-manciot/ppa/raw/master/Ubuntu xenial/stable amd64 Packages
 *** 0.3.9~git20160915.eb33c65-14 100
        100 /var/lib/dpkg/status**
     0.3.9~git20160908.b4cbff9-14 500
        500 https://gitlab.com/jean-christophe-manciot/ppa/raw/master/Ubuntu xenial/stable amd64 Packages
     0.3.8-14 500
        500 https://gitlab.com/jean-christophe-manciot/ppa/raw/master/Ubuntu xenial/stable amd64 Packages
     0.3.6-14 500
        500 https://gitlab.com/jean-christophe-manciot/ppa/raw/master/Ubuntu xenial/stable amd64 Packages
```
```
apt policy apt
apt:
  Installed: 1.2.14
  Candidate: 1.2.14
  Version table:
 ***** 1.2.14 500
        500 https://gitlab.com/jean-christophe-manciot/ppa/raw/master/Ubuntu xenial/stable amd64 Packages
        100 /var/lib/dpkg/status**
     1.2.13 500
        500 https://gitlab.com/jean-christophe-manciot/ppa/raw/master/Ubuntu xenial/stable amd64 Packages
     1.2.12~ubuntu16.04.1 500
        500 http://bouyguestelecom.ubuntu.lafibre.info/ubuntu xenial-updates/main amd64 Packages
     1.2.10ubuntu1 500
        500 http://bouyguestelecom.ubuntu.lafibre.info/ubuntu xenial/main amd64 Packages

apt policy git
git:
  Installed: 1:2.10.0-14
  Candidate: 1:2.10.0-14
  Version table:
 ***** 1:2.10.0-14 500
        500 https://gitlab.com/jean-christophe-manciot/ppa/raw/master/Ubuntu xenial/stable amd64 Packages
        100 /var/lib/dpkg/status**
     1:2.9.3-14 500
        500 https://gitlab.com/jean-christophe-manciot/ppa/raw/master/Ubuntu xenial/stable amd64 Packages
     1:2.7.4-0ubuntu1 500
        500 http://bouyguestelecom.ubuntu.lafibre.info/ubuntu xenial/main amd64 Packages
```
Other information with dpkg:
```
dpkg -l network-manager-strongswan
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                  Version                 Architecture            Description
+++-=====================================-=======================-=======================-===============================================================================
ii  network-manager-strongswan            1.3.1-14                amd64                   This package provides an IKEv2 IPSec VPN plugin for strongswan

dpkg -l ntopng
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                  Version                 Architecture            Description
+++-=====================================-=======================-=======================-===============================================================================
ii  ntopng                                2.4.1~git20160917.6bd1f amd64                   High-Speed Web-based Traffic Analysis and Flow Collection

dpkg -l libgegl-0.3-0
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                  Version                 Architecture            Description
+++-=====================================-=======================-=======================-===============================================================================
ii  libgegl-0.3-0                         0.3.9~git20160915.eb33c amd64                   GEGL (Generic Graphics Library) is a graph based image processing framework
```
Also, **dpkg has no issue not installing them again**:
```
dpkg -iE libgegl-0.3-0_0.3.9~git20160915.eb33c65-14_amd64.deb 
dpkg: version 0.3.9~git20160915.eb33c65-14 of libgegl-0.3-0 already installed, skipping
root@samsung-ubuntu:/var/cache/apt/archives# dpkg -iE network-manager-strongswan_1.3.1-14_amd64.deb 
dpkg: version 1.3.1-14 of network-manager-strongswan already installed, skipping
root@samsung-ubuntu:/var/cache/apt/archives# dpkg -iE ntopng_2.4.1~git20160917.6bd1fee-14_amd64.deb 
dpkg: version 2.4.1~git20160917.6bd1fee-14 of ntopng already installed, skipping
```
I don't see anything special about the dependencies of the 3 packages.
My **/etc/apt/apt.conf** is empty and **/etc/apt/apt-file.conf** has not been altered from default values
[apt-file.conf.txt](https://github.com/Debian/apt/files/478622/apt-file.conf.txt)
I don't use apt pinning: there's **no /etc/apt/preferences**. 
My **apt-config dump**: [apt-config.dump.txt](https://github.com/Debian/apt/files/478633/apt-config.dump.txt)
My **/etc/apt/sources.list**: [sources.list.txt](https://github.com/Debian/apt/files/478635/sources.list.txt)
My **/etc/apt/sources.list.d**: [sources.list.d.zip](https://github.com/Debian/apt/files/478637/sources.list.d.zip)

Finally, this issue seems **directly related** to an [old bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=351056).
@mvo5

**Comment by julian-klode** [comment] 2016-09-18 10:40
There must be some special formatting in the package control file that dpkg normalizes differently than apt does, and thus APT considers the remote version as a different version, because they have a different hash.

The following fields must be the same in the Packages file and /var/lib/dpkg status: "Installed-Size",
"Depends", "Pre-Depends",  "Conflicts", "Breaks", "Replaces".  All spaces are ignored, all values are transformed to lowercase, and <= and >= are normalized into < and >.

**Comment by jean-christophe-manciot** [comment] 2016-09-18 10:56
- for one of the 3 (network-manager-strongswan), there is no "Depends", "Pre-Depends", "Conflicts", "Breaks", "Replaces". fields.
- for the latter, the control file [control.txt](https://github.com/Debian/apt/files/478647/control.txt) indicates the same "Installed-Size": 256 as within /var/lib/dpkg/status.
```
Package: network-manager-strongswan
Priority: extra
Section: net
Installed-Size: 256
Maintainer: Jean-Christophe Manciot <manciot.jeanchristophe@gmail.com>
Architecture: amd64
Version: 1.3.1-14
Depends: libart-2.0-2,libatk1.0-0,libavahi-client3,libavahi-common3,libavahi-glib1,libbonobo2-0,libbonoboui2-0,libc6,libcairo2,libcanberra0,libdatrie1,libdbus-1-3,libdbus-glib-1-2,libexpat1,libffi6,libfontconfig1,libfreetype6,libgail18,libgconf-2-4,libgcrypt20,libgdk-pixbuf2.0-0,libglib2.0-0,libglib2.0-0-dbg,libglib2.0-0-refdbg,libgmp10,libgnome-2-0,libgnomecanvas2-0,libgnome-keyring0,libgnomeui-0,libgnomevfs2-0,libgnutls30,libgpg-error0,libgraphite2-3,libgtk2.0-0,libharfbuzz0b,libhogweed4,libice6,libidn11,libltdl7,liblzma5,libnettle6,libnm-glib-vpn1,libnm-util2,libogg0,liborbit-2-0,libp11-kit0,libpango-1.0-0,libpangocairo-1.0-0,libpangoft2-1.0-0,libpcre3,libpixman-1-0,libpng12-0,libpopt0,libselinux1,libsm6,libsystemd0,libtasn1-6,libtdb1,libthai0,libuuid1,libvorbis0a,libvorbisfile3,libx11-6,libxau6,libxcb1,libxcb-render0,libxcb-shm0,libxcomposite1,libxcursor1,libxdamage1,libxdmcp6,libxext6,libxfixes3,libxi6,libxinerama1,libxml2,libxrandr2,libxrender1,zlib1g
Provides: network-manager-strongswan
Description: This package provides an IKEv2 IPSec VPN plugin for strongswan
```

**Comment by jean-christophe-manciot** [comment] 2016-09-18 11:13
libgegl has a "Replaces" field:
```
Package: libgegl-0.3-0
Priority: extra
Section: graphics
Installed-Size: 40380
Maintainer: Jean-Christophe Manciot <manciot.jeanchristophe@gmail.com>
Architecture: amd64
Version: 0.3.9~git20160915.eb33c65-14
Depends: libamd2.4.1,libasound2,libasyncns0,libbabl-0.1-0,libblas3,libc6,libcaca0,libcairo2,libcamd2.4.1,libccolamd2.9.1,libcholmod3.0.6,libcolamd2.9.1,libcroco3,libdatrie1,libdbus-1-3,libexpat1,libffi6,libflac8,libfontconfig1,libfreetype6,libgcc1,libgcrypt20,libgdk-pixbuf2.0-0,libgfortran3,libglib2.0-0,libglib2.0-0-dbg,libglib2.0-0-refdbg,libgomp1,libgpg-error0,libgraphite2-3,libharfbuzz0b,libilmbase12,libjasper1,libjbig0,libjpeg-turbo8,libjson-c2,libjson-glib-1.0-0,liblapack3,liblzma5,libncursesw5,libobasis5.2-core,libogg0,libopenexr22,libpango-1.0-0,libpangocairo-1.0-0,libpangoft2-1.0-0,libpcre3,libpixman-1-0,libpng12-0,libpulse0,libquadmath0,libraw15,librsvg2-2,libsdl1.2debian,libselinux1,libslang2,libsndfile1,libspiro0,libstdc++6,libsuitesparseconfig4.4.6,libsystemd0,libthai0,libtiff5,libtinfo5,libumfpack5.7.1,libvorbis0a,libvorbisenc2,libwebp5,libwrap0,libx11-6,libxau6,libxcb1,libxcb-render0,libxcb-shm0,libxdmcp6,libxext6,libxml2,libxrender1,zlib1g
Provides: libgegl-0.3-0
Replaces: gegl,libgegl-dev,libgegl-doc,libgegl-0.3-0-dbg
Description: GEGL (Generic Graphics Library) is a graph based image processing framework
```
ntopng has "Replaces" & "Conflicts" fields:
```
Package: ntopng
Priority: extra
Section: net
Installed-Size: 80560
Maintainer: Jean-Christophe Manciot <manciot.jeanchristophe@gmail.com>
Architecture: amd64
Version: 2.4.1~git20160917.6bd1fee-14
Depends: libasn1-8-heimdal,libc6,libcairo2,libcomerr2,libdatrie1,libdbi1,libdbus-1-3,libexpat1,libffi6,libfontconfig1,libfreetype6,libgcc1,libgcrypt20,libgeoip1,libglib2.0-0-dbg,libglib2.0-0-refdbg,libgmp10,libgnutls30,libgpg-error0,libgraphite2-3,libgssapi3-heimdal,libgssapi-krb5-2,libharfbuzz0b,libhcrypto4-heimdal,libheimbase1-heimdal,libheimntlm0-heimdal,libhiredis0.13,libhogweed4,libhx509-5-heimdal,libidn11,libjson-c2,libk5crypto3,libkeyutils1,libkrb5-26-heimdal,libkrb5-3,libkrb5support0,libldap-2.4-2,libluajit-5.1-2,liblzma5,libmariadb2,libnettle6,libnl-3-200,libnl-genl-3-200,libobasis5.2-core,libp11-kit0,libpango-1.0-0,libpangocairo-1.0-0,libpangoft2-1.0-0,libpcap0.8,libpcre3,libpixman-1-0,libpng12-0,libroken18-heimdal,librrd4,librtmp1,libsasl2-2,libselinux1,libsodium18,libsqlite3-0,libssl1.0.0,libstdc++6,libsystemd0,libtasn1-6,libthai0,libudev1,libusb-1.0-0,libwind0-heimdal,libx11-6,libxau6,libxcb1,libxcb-render0,libxcb-shm0,libxdmcp6,libxext6,libxml2,libxrender1,libzmq5,ndpi,redis-server,zlib1g
Provides: ntopng
Conflicts: ntop,ntop-data,ntop-dbg
Replaces: ntopng-data,ntopng-doc,ntopng-dbg
Description: High-Speed Web-based Traffic Analysis and Flow Collection
```

**Comment by julian-klode** [comment] 2016-09-18 11:14
Reproduced. Looking into it.

**Comment by julian-klode** [comment] 2016-09-18 11:24
The problem here really is the formatting of the Depends field. Your repository has no spaces after the commas leading to a line length < 1024. dpkg re-adds the spaces, resulting in the dependency line being longer than 1024 characters, which is the maximum line length APT supports here and it thus ignores the Depends field for the calculation of its version hash in the dpkg status file, and thus the repo and the status file have different hashes.

I have a fix for this.

**Comment by jean-christophe-manciot** [comment] 2016-09-18 11:55
I doubt this is the core reason for this issue, although raising the max value for the Depends field seems necessary.
I have many other control files which have much longer Depends field, **without any issue** with the upgrade. For instance, qemu:
```
Package: qemu
Priority: extra
Section: utils
Installed-Size: 24760
Maintainer: Jean-Christophe Manciot <manciot.jeanchristophe@gmail.com>
Architecture: amd64
Version: 1:2.7.0-14
Depends: firefox,glusterfs-common,lib32gcc1,libacl1,libaio1,libasn1-8-heimdal,libasound2,libasyncns0,libatk1.0-0,libattr1,libblkid1,libbluetooth3,libboost-iostreams1.58.0,libboost-random1.58.0,libboost-system1.58.0,libboost-thread1.58.0,libbrlapi0.6,libbz2-1.0,libc6,libcaca0,libcacard0,libcairo2,libcap2,libcap-ng0,libcelt051,libcomerr2,libcurl3,libdatrie1,libdbus-1-3,libdrm2,libepoxy0,libexpat1,libfdt1,libffi6,libflac8,libfontconfig1,libfreetype6,libgbm1,libgcc1,libgcrypt20,libgdk-pixbuf2.0-0,libglib2.0-0,libglib2.0-0-dbg,libglib2.0-0-refdbg,libgmp10,libgnutls30,libgpg-error0,libgraphite2-3,libgssapi3-heimdal,libgssapi-krb5-2,libgtk2.0-0,libharfbuzz0b,libhcrypto4-heimdal,libheimbase1-heimdal,libheimntlm0-heimdal,libhogweed4,libhx509-5-heimdal,libidn11,libiscsi2,libjemalloc1,libjpeg-turbo8,libjson-c2,libk5crypto3,libkeyutils1,libkrb5-26-heimdal,libkrb5-3,libkrb5support0,libldap-2.4-2,liblz4-1,liblzma5,liblzo2-2,libncurses5,libncursesw5,libnettle6,libnfs8,libnspr4,libnss3,libnuma1,libobasis5.2-core,libogg0,libopus0,libp11-kit0,libpango-1.0-0,libpangocairo-1.0-0,libpangoft2-1.0-0,libpcre3,libpixman-1-0,libpng12-0,libpulse0,librados2,librbd1,libroken18-heimdal,librtmp1,libsasl2-2,libsdl1.2debian,libseccomp2,libselinux1,libslang2,libsnappy1v5,libsndfile1,libspice-server1,libsqlite3-0,libssh2-1,libssl1.0.0,libstdc++6,libsystemd0,libtasn1-6,libthai0,libtinfo5,libudev1,libusb-1.0-0,libusbredirparser1,libuuid1,libvorbis0a,libvorbisenc2,libwayland-client0,libwayland-server0,libwind0-heimdal,libwrap0,libx11-6,libxau6,libxcb1,libxcb-render0,libxcb-shm0,libxcomposite1,libxcursor1,libxdamage1,libxdmcp6,libxen-4.6,libxenstore3.0,libxext6,libxfixes3,libxi6,libxinerama1,libxrandr2,libxrender1,qemu-system-common,zlib1g
Provides: qemu
Replaces: ipxe-qemu,qemu-doc,qemu-kvm,qemu-system-common,qemu-system-x86,qemu-utils
Description: Generic and open source machine emulator and virtualizer
```

**Comment by julian-klode** [comment] 2016-09-18 11:59
Longer is not the problem. The problem is if it is shorter than 1024 characters without spaces (apt includes it in the hash then) and suddenly longer than 1024 when dpkg re-adds the spaces (apt does not include it in the hash => hash different for status file).

I'd advise you to not mangle the depends fields by removing the spaces there. Use the normal specified format like everyone else:  Spaces after comma, spaces before ( and space after comparison operator, that is: pkg, pkg (>= 1.0) - NOT: pkg,pkg(>=1.0).

**Comment by julian-klode** [comment] 2016-09-18 11:59
Anyway, this is basically fixed, I'm just doing some cleanup in the test case name...

**Comment by julian-klode** [comment] 2016-09-18 16:52
Hmm. the commit was autopushed by the mirroring tool, but apparently the issue was not closed. Doing this now. I'll also pick that into the 1.2.y (xenial) branch for the upcoming 1.2.15 stable release update.

**Closed by julian-klode** 2016-09-18 16:52 UTC
Labels: bug

**Comment by jean-christophe-manciot** [comment] 2016-09-21 10:50
Successfully tested with 1.3. :)
